CREATE TABLE `ash`.`clubs` (
  `CLUBID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45),
  PRIMARY KEY(`CLUBID`)
);

CREATE TABLE `ash`.`club_points` (
  `CLUBID` INT NOT NULL,
  `TOURNAMENTID` INT NOT NULL,
  `POINTS` INT NULL,
  PRIMARY KEY (`CLUBID`),
  INDEX `TOURNAMENT` (`TOURNAMENTID` ASC)
);

CREATE TABLE `ash`.`organizer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLUBID` INT,
  `INFO` VARCHAR(1000),
  PRIMARY KEY(`ID`),
  INDEX `club` (`CLUBID` ASC)
);

CREATE TABLE `ash`.`places` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` INT,
  `lon` FLOAT,
  `lat` FLOAT,
  PRIMARY KEY(`ID`)
);

CREATE TABLE `ash`.`tournament` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `ORGID` INT NOT NULL,
  `PLACE` INT NULL,
  `DATE` DATE NULL,
  `END_REGISTRATION_DATE` DATE NULL,
  PRIMARY KEY (`ID`),
  INDEX `org` (`ORGID` ASC),
  INDEX `place` (`PLACE` ASC)
);

